### ISSUE TITLE
Change Creative Commons License

### ISSUE THREAD

**Issue by makerchad** [nationofmakers/maker-event-playbook#24]
Change Creative Commons License to MIT or like licensing type.

**Comment by candykisses2112** [comment]
All resulting deliverables to be licensed under the Apache or
MIT open source license.

**Comment by candykisses2112** [comment]
Decision was made to go with MIT open source license.

**Comment by digitalman2112** [comment]
Code is in footer
https://github.com/nationofmakers/maker-event-playbook/blob/2460cb9593d44fd702dd96ee1a13188ad6c40063/_includes/footer.html#L8

**Comment by raster** [comment]
License links to this page: https://mit-license.org/ but we might want to create our own license file for our site and link to that version. Filling in the part that shows <copyright holders>

More info here: https://github.com/remy/mit-license

(Related: There is a code of conduct there as well)

**Comment by raster** [comment]
Added MIT license within the site.
