### ISSUE TITLE
Determine proper link format in markdown and html

### ISSUE THREAD

**Issue by digitalman2112** [nationofmakers/maker-event-playbook#27]
https://github.blog/2016-12-05-relative-links-for-github-pages/

Want to make sure that any GH pages on forked repos retain local links

**Comment by raster** [comment]
See Google Doc (link in Slack) for findings and questions regarding links.

**Comment by raster** [comment]
Can I reassign this to @schneidy ? ;)

**Comment by digitalman2112** [comment]
Good example of using the relativeurl syntax in the footer: https://github.com/nationofmakers/maker-event-playbook/blob/3d01229645045aec3c2b605b5e68ad94db8cfec8/_includes/footer.html#L5
