### ISSUE TITLE
Footer images url pattern broken

### ISSUE THREAD

**Issue by digitalman2112** [nationofmakers/maker-event-playbook#31]
Relative URLs in footer images now broken

![image](https://user-images.githubusercontent.com/452840/77849234-23ee2a00-7198-11ea-8df4-1c0a00fb967b.png)

![image](https://user-images.githubusercontent.com/452840/77849244-3a948100-7198-11ea-9ec2-0f4bf510f0f3.png)

from footer.html:
img src="{{ "images/nom_logo.png" }}" alt="Nation of Makers logo"/>

**Comment by schneidy** [comment]
@digitalman2112 What page is this breaking on?

Never mind, found it.
