### ISSUE TITLE
Search json URL broken on canonical GH pages, works on hosted forks

### ISSUE THREAD

**Issue by digitalman2112** [nationofmakers/maker-event-playbook#33]
https://github.com/nationofmakers/maker-event-playbook/blob/97ff91819c1a9e842d954efb2a3a4a6fca6ffdfb/_includes/topnav.html#L69

![image](https://user-images.githubusercontent.com/452840/77850992-4b4af400-71a4-11ea-9d8f-b48839ea1ec5.png)

On the canonical hosted pages, the maker-event-playbook section is duplicated twice and throws a 404, however on a hosted fork, it works properly

![image](https://user-images.githubusercontent.com/452840/77851021-759cb180-71a4-11ea-87ec-bd2c35c33a51.png)

**Comment by digitalman2112** [comment]
@schneidy - I'm assigning these to you since you've done more work with URLs recently, but if you want to get on a call and tag-team it, happy to help.

**Comment by schneidy** [comment]
It now works.
